version: 2.1

jobs:
  test:
    docker:
      - image: maven:3.8.6-openjdk-18  # Maven image with OpenJDK 18
    steps:
      - checkout  # Checkout the code from the repo
      - run:
          name: Run tests
          command: mvn clean test  # Execute tests

workflows:
  version: 2
  test:
    jobs:
      - test