version: 2.1

jobs:
  test:
    docker:
      - image: openjdk:18-jdk  # Use an image that includes OpenJDK (for Spring Boot)
        environment:
          JAVA_HOME: /usr/local/openjdk-18
    steps:
      - checkout  # Checkout the code from the repo
      - run:
          name: Install Maven
          command: |
            apt-get update
            apt-get install -y maven
      - run:
          name: Run tests
          command: mvn clean test  # Execute tests

workflows:
  version: 2
  test:
    jobs:
      -test
